version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis